#!/usr/bin/env node
/**
 * PostToolUse Hook: removes junk from the project root.
 *
 * Two classes, and until 2026-08-20 only the first one was implemented while the rule
 * promised both:
 *
 *  1. GENERATOR ARTEFACTS — files whose NAME is a code fragment (`flex`, `mb-6`,
 *     `BigInt`, `void)`), the residue of a model writing a filename where a value
 *     belonged. Size-capped at 100 bytes so a real file that happens to be called
 *     `10` is never touched.
 *  2. OS AND TOOLCHAIN DEBRIS — `.DS_Store`, `__pycache__`, `.pytest_cache`,
 *     `Thumbs.db`. `rules/intelligence.md` #4 names exactly these ("Delete junk (temp
 *     files, .DS_Store, __pycache__) immediately"), and this helper skipped every one
 *     of them: dotfiles were excluded wholesale by `name.startsWith('.')`, and
 *     `__pycache__` matched no pattern AND would have failed the isFile() test as a
 *     directory. Measured 2026-08-20 while writing the first fixture for this hook —
 *     both survived a run in a throwaway root. The rule and the code had been saying
 *     different things for as long as both existed.
 *
 * The two classes are matched separately BECAUSE they failed for two different
 * reasons: one needs an exception from the dotfile skip, the other needs directory
 * handling. Fixing only the pattern list would have closed half of it and looked done.
 *
 * Debris removal is by EXACT NAME, never by pattern: everything in that list is
 * regenerated by the tool that made it, so deleting it costs nothing — and an exact
 * list cannot grow teeth the way a regex can.
 */
const fs = require('fs');
const path = require('path');

const ROOT = process.env.CLAUDE_PROJECT_DIR || path.join(__dirname, '..', '..');

// Class 1: a filename that is really a code fragment. Size-capped.
const junkPatterns = [
  /^[{(,;)}]+$/,          // punctuation-only: {, (, ,, ;, }
  /^\d+$/,                 // number-only: 10
  /^(flex|mb-\d|px-\d|void\)|BigInt|undefined|null|NaN|true|false)$/,
  /\.(count|type|div)$/    // nonsense extensions
];

// Class 2: OS/toolchain debris, exact names only, regenerated by their own tool.
const DEBRIS_FILES = new Set(['.DS_Store', 'Thumbs.db', 'desktop.ini']);
const DEBRIS_DIRS = new Set(['__pycache__', '.pytest_cache', '.ruff_cache']);

try {
  const items = fs.readdirSync(ROOT);
  const deleted = [];

  for (const name of items) {
    if (name === 'node_modules') continue;

    const full = path.join(ROOT, name);
    let stat;
    try { stat = fs.lstatSync(full); } catch (e) { continue; }
    // Never follow a link: the target may live outside the project entirely.
    if (stat.isSymbolicLink()) continue;

    if (DEBRIS_FILES.has(name) && stat.isFile()) {
      try { fs.unlinkSync(full); deleted.push(name); } catch (e) { /* skip */ }
      continue;
    }
    if (DEBRIS_DIRS.has(name) && stat.isDirectory()) {
      try { fs.rmSync(full, { recursive: true, force: true }); deleted.push(`${name}/`); }
      catch (e) { /* skip */ }
      continue;
    }

    if (name.startsWith('.')) continue;   // no other dotfile is ever touched

    let isJunk = false;
    for (const pattern of junkPatterns) {
      if (pattern.test(name)) { isJunk = true; break; }
    }
    if (isJunk && stat.isFile() && stat.size < 100) {
      try { fs.unlinkSync(full); deleted.push(name); } catch (e) { /* skip */ }
    }
  }

  if (deleted.length > 0) {
    console.error(`[junk-cleaner] removed: ${deleted.join(', ')}`);
  }
} catch (e) { /* a cleaner must never break a turn */ }
