#!/usr/bin/env python3
"""GENERATE a routing index for an invariant register — one line per class.

WHY (measured on the proving brain): the shared memory and the private memory route through
generated or linted indexes; the invariant register had none — 222,106 bytes in ONE file by
2026-10-09 (115 KB on 2026-08-30). Whoever asks "which classes exist, and which are still
open?" reads the whole register or greps. The operator's order (2026-08-30): "everything
should run on the same principles, not different index systems" — generated, not hand-kept;
routing length per entry; full text stays in the detail file; cost per lookup measured.

One line per `## ` block: title, status (cut), and what HOLDS the class — `pattern` (a
search re-runs), `tool` (a named tool re-checks), `no` (a judgement, with its reason in the
register), or `prose` (nothing re-checks it). The register stays the detail level.
WHAT IT NEVER DOES: summarise, rephrase or shorten an entry; it only cuts the status field.

Usage: invariant-index.py <register.md> [--write]
       Without --write it prints the index and the size comparison.
       --write writes <register-stem>-index.md beside the register.
Exit 0 always (a generator, not a check).
"""
import importlib.util
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8", newline="\n")
except (AttributeError, ValueError):
    pass

STATUS_CHARS = 90

_spec = importlib.util.spec_from_file_location("invariant_check", Path(__file__).with_name("invariant-check.py"))
_ic = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_ic)


def carrier(b):
    if b.get("pattern"):
        return "pattern"
    mech = (b.get("mechanizable") or "").strip().lower()
    if mech.startswith("tool"):
        return "tool"
    if mech.startswith("no"):
        return "no"
    return "prose"


def cut(text, n):
    text = " ".join((text or "").split())
    return text if len(text) <= n else text[: n - 1].rstrip() + "…"


def build(register):
    _, blocks = _ic.parse(register)
    out = [f"# Index — {register.name}", "",
           f"Generated by invariant-index.py from `{register.name}` — do not edit; the register is the detail level.",
           "One line per class: title · status · what holds it (pattern / tool / no = judgement / prose = nothing re-checks).",
           ""]
    for b in blocks:
        out.append(f"- **{b['id']}** · {cut(b.get('status') or '?', STATUS_CHARS)} · {carrier(b)}")
    return "\n".join(out) + "\n"


def main(argv):
    args = [a for a in argv if a != "--write"]
    if len(args) != 1:
        print("usage: invariant-index.py <register.md> [--write]")
        return 0
    register = Path(args[0])
    text = build(register)
    if "--write" in argv:
        target = register.with_name(register.stem + "-index.md")
        with open(target, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        print(f"written: {target.name} ({len(text)} chars)")
    else:
        sys.stdout.write(text)
    full = len(register.read_text(encoding="utf-8"))
    print(f"lookup: {len(text)} chars instead of {full} ({full / max(len(text), 1):.0f}x less)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
